services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: tr33p
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fileserver
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  server:
    container_name: server
    build: .
    environment:
      JDBC_DATABASE_URL: jdbc:postgresql://postgres:5432/fileserver
      ENCRYPTION_KEY: vevnwecjc43cece[socmqweokcm34c[3
      AUTH_USERNAME: serv
      AUTH_PASSWORD: testpass
    depends_on:
      - postgres
    ports:
      - "5050:5050"