- hosts: test

  tasks:
  - name: install git, curl
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    loop:
      - git
      - curl
      - make

  - name: download docker shell script
    ansible.builtin.command:
      cmd: curl -fsSL https://get.docker.com -o get-docker.sh
  
  - name: change docker execute rights
    ansible.builtin.command:
      cmd: chmod +x ./get-docker.sh
    
  - name: install docker
    ansible.builtin.command:
      cmd: ./get-docker.sh
    
  - name: install docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: u+x,g+x,o+x

  - name: open 5050 port
    ansible.builtin.shell:
      cmd: iptables -A INPUT -p tcp --dport 5050 -j ACCEPT

  - name: save iptables
    ansible.builtin.shell:
      cmd: iptables-save

  - name: ufw config
    ansible.builtin.shell: ufw allow 5050/tcp

  - name: clone project
    ansible.builtin.git:
      repo: https://github.com/tre3p/home-fileserver.git
      dest: /usr/app
      version: test
  
  - name: start app
    command: make start-demo
    args:
      chdir: /usr/app