name: Deploy on Test Stand

on:
  push:
    branches:
      - test

jobs:     
  deployAnsible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/workflows
      with: 
        playbook: deploy.yml
        inventory: ${{secrets.STAND_ADDRESS}}
        key: ${{secrets.SSH_KEY}}
