name: Deploy on Test Stand

on:
  push:
    branches:
      - test

jobs:     
  deployAnsible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dawidd6/action-ansible-playbook@v2
      with: 
        playbook: deploy.yml
        directory: ./.github/workflows
        inventory: |
          [all]
          ${{ secrets.STAND_ADDRESS }} ansible_user=${{ secrets.DEPLOY_USER }}
        key: ${{secrets.SSH_KEY}}
